# Generated by Django 6.0.7 on 2026-08-07 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Courses',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.URLField()),
                ('slug', models.CharField(choices=[('Language', 'LANGUAGE'), ('Professional', 'PROFESSIONAL'), ('Training', 'TRAINING')], max_length=15)),
                ('title', models.CharField(choices=[('German', 'GERMAN LANGUAGE'), ('Korean', 'KOREAN LANGUAGE'), ('Accounting', 'ACCOUNTING TRAINING'), ('Computer', 'COMPUTER TRAINING')], max_length=15)),
                ('subHeading', models.TextField()),
                ('description', models.TextField()),
                ('duration', models.CharField(choices=[('6 months', 'Half a year'), ('3 months', 'Quarter a year'), ('12 months', 'A year')], max_length=15)),
                ('mode', models.CharField(choices=[('Online', 'ONLINE'), ('Offline', 'OFFLINE'), ('Online or Offline', 'BOTH')], max_length=20)),
                ('level', models.CharField(choices=[('Beginner to Intermediate', 'BEGINNER TO INTERMEDIATE'), ('Intermediate to Advanced', 'INTERMEDIATE TO ADVANCED'), ('Beginner to Advanced', 'BEGINNER TO ADVANCED')], max_length=50)),
                ('classTiming', models.CharField(choices=[('Morning Only', 'BEGINNER TO INTERMEDIATE'), ('Afternoon Only', 'INTERMEDIATE TO ADVANCED'), ('Evening Only', 'BEGINNER TO ADVANCED'), ('Morning and Afternoon', 'BEGINNER TO ADVANCED'), ('Morning and Evening', 'BEGINNER TO ADVANCED'), ('Afternoon and Evening', 'BEGINNER TO ADVANCED')], max_length=50)),
                ('certificate', models.BooleanField(default=False)),
                ('languageLevel1', models.CharField(blank=True, choices=[('A1', 'A1-GERMAN'), ('A2', 'A2-GERMAN'), ('B1', 'B1-GERMAN'), ('B2', 'B2-GERMAN'), ('TOPIK I', 'TOPIK I-KOREAN'), ('TOPIK II', 'TOPIK II-KOREAN'), ('Beginner', 'BEGINNER-KOREAN'), ('Intermediate', 'INTERMEDIATE-KOREAN'), ('Advanced', 'ADVANCED-KOREAN')], max_length=15)),
                ('languageLevel2', models.CharField(blank=True, choices=[('A1', 'A1-GERMAN'), ('A2', 'A2-GERMAN'), ('B1', 'B1-GERMAN'), ('B2', 'B2-GERMAN'), ('TOPIK I', 'TOPIK I-KOREAN'), ('TOPIK II', 'TOPIK II-KOREAN'), ('Beginner', 'BEGINNER-KOREAN'), ('Intermediate', 'INTERMEDIATE-KOREAN'), ('Advanced', 'ADVANCED-KOREAN')], max_length=15)),
                ('languageLevel3', models.CharField(blank=True, choices=[('A1', 'A1-GERMAN'), ('A2', 'A2-GERMAN'), ('B1', 'B1-GERMAN'), ('B2', 'B2-GERMAN'), ('TOPIK I', 'TOPIK I-KOREAN'), ('TOPIK II', 'TOPIK II-KOREAN'), ('Beginner', 'BEGINNER-KOREAN'), ('Intermediate', 'INTERMEDIATE-KOREAN'), ('Advanced', 'ADVANCED-KOREAN')], max_length=15)),
                ('languageLevel4', models.CharField(blank=True, choices=[('A1', 'A1-GERMAN'), ('A2', 'A2-GERMAN'), ('B1', 'B1-GERMAN'), ('B2', 'B2-GERMAN'), ('TOPIK I', 'TOPIK I-KOREAN'), ('TOPIK II', 'TOPIK II-KOREAN'), ('Beginner', 'BEGINNER-KOREAN'), ('Intermediate', 'INTERMEDIATE-KOREAN'), ('Advanced', 'ADVANCED-KOREAN')], max_length=15)),
                ('feature1', models.CharField(choices=[('interactive_classes', 'Interactive Classes'), ('native_pronunciation', 'Native Pronunciation'), ('speaking_sessions', 'Speaking Sessions'), ('weekly_exams', 'Weekly Exams'), ('study_materials', 'Study Materials'), ('mock_interviews', 'Mock Interviews'), ('visa_guidance', 'Visa Guidance'), ('career_counselling', 'Career Counselling'), ('hangul_writing', 'Hangul Writing'), ('speaking_practice', 'Speaking Practice'), ('listening_exercises', 'Listening Exercises'), ('topik_preparation', 'TOPIK Preparation'), ('weekly_assessments', 'Weekly Assessments'), ('small_batch_classes', 'Small Batch Classes'), ('career_guidance', 'Career Guidance'), ('tally_erp', 'Tally ERP'), ('quickbooks', 'QuickBooks'), ('vat_taxation', 'VAT & Taxation'), ('payroll', 'Payroll'), ('financial_statements', 'Financial Statements'), ('practical_projects', 'Practical Projects'), ('interview_preparation', 'Interview Preparation'), ('certificate', 'Certificate'), ('ms_word', 'MS Word'), ('excel', 'Excel'), ('powerpoint', 'PowerPoint'), ('internet', 'Internet'), ('email', 'Email'), ('typing_skills', 'Typing Skills'), ('basic_programming', 'Basic Programming'), ('project_work', 'Project Work')], max_length=50)),
                ('feature2', models.CharField(choices=[('interactive_classes', 'Interactive Classes'), ('native_pronunciation', 'Native Pronunciation'), ('speaking_sessions', 'Speaking Sessions'), ('weekly_exams', 'Weekly Exams'), ('study_materials', 'Study Materials'), ('mock_interviews', 'Mock Interviews'), ('visa_guidance', 'Visa Guidance'), ('career_counselling', 'Career Counselling'), ('hangul_writing', 'Hangul Writing'), ('speaking_practice', 'Speaking Practice'), ('listening_exercises', 'Listening Exercises'), ('topik_preparation', 'TOPIK Preparation'), ('weekly_assessments', 'Weekly Assessments'), ('small_batch_classes', 'Small Batch Classes'), ('career_guidance', 'Career Guidance'), ('tally_erp', 'Tally ERP'), ('quickbooks', 'QuickBooks'), ('vat_taxation', 'VAT & Taxation'), ('payroll', 'Payroll'), ('financial_statements', 'Financial Statements'), ('practical_projects', 'Practical Projects'), ('interview_preparation', 'Interview Preparation'), ('certificate', 'Certificate'), ('ms_word', 'MS Word'), ('excel', 'Excel'), ('powerpoint', 'PowerPoint'), ('internet', 'Internet'), ('email', 'Email'), ('typing_skills', 'Typing Skills'), ('basic_programming', 'Basic Programming'), ('project_work', 'Project Work')], max_length=50)),
                ('feature3', models.CharField(choices=[('interactive_classes', 'Interactive Classes'), ('native_pronunciation', 'Native Pronunciation'), ('speaking_sessions', 'Speaking Sessions'), ('weekly_exams', 'Weekly Exams'), ('study_materials', 'Study Materials'), ('mock_interviews', 'Mock Interviews'), ('visa_guidance', 'Visa Guidance'), ('career_counselling', 'Career Counselling'), ('hangul_writing', 'Hangul Writing'), ('speaking_practice', 'Speaking Practice'), ('listening_exercises', 'Listening Exercises'), ('topik_preparation', 'TOPIK Preparation'), ('weekly_assessments', 'Weekly Assessments'), ('small_batch_classes', 'Small Batch Classes'), ('career_guidance', 'Career Guidance'), ('tally_erp', 'Tally ERP'), ('quickbooks', 'QuickBooks'), ('vat_taxation', 'VAT & Taxation'), ('payroll', 'Payroll'), ('financial_statements', 'Financial Statements'), ('practical_projects', 'Practical Projects'), ('interview_preparation', 'Interview Preparation'), ('certificate', 'Certificate'), ('ms_word', 'MS Word'), ('excel', 'Excel'), ('powerpoint', 'PowerPoint'), ('internet', 'Internet'), ('email', 'Email'), ('typing_skills', 'Typing Skills'), ('basic_programming', 'Basic Programming'), ('project_work', 'Project Work')], max_length=50)),
                ('feature4', models.CharField(choices=[('interactive_classes', 'Interactive Classes'), ('native_pronunciation', 'Native Pronunciation'), ('speaking_sessions', 'Speaking Sessions'), ('weekly_exams', 'Weekly Exams'), ('study_materials', 'Study Materials'), ('mock_interviews', 'Mock Interviews'), ('visa_guidance', 'Visa Guidance'), ('career_counselling', 'Career Counselling'), ('hangul_writing', 'Hangul Writing'), ('speaking_practice', 'Speaking Practice'), ('listening_exercises', 'Listening Exercises'), ('topik_preparation', 'TOPIK Preparation'), ('weekly_assessments', 'Weekly Assessments'), ('small_batch_classes', 'Small Batch Classes'), ('career_guidance', 'Career Guidance'), ('tally_erp', 'Tally ERP'), ('quickbooks', 'QuickBooks'), ('vat_taxation', 'VAT & Taxation'), ('payroll', 'Payroll'), ('financial_statements', 'Financial Statements'), ('practical_projects', 'Practical Projects'), ('interview_preparation', 'Interview Preparation'), ('certificate', 'Certificate'), ('ms_word', 'MS Word'), ('excel', 'Excel'), ('powerpoint', 'PowerPoint'), ('internet', 'Internet'), ('email', 'Email'), ('typing_skills', 'Typing Skills'), ('basic_programming', 'Basic Programming'), ('project_work', 'Project Work')], max_length=50)),
                ('feature5', models.CharField(blank=True, choices=[('interactive_classes', 'Interactive Classes'), ('native_pronunciation', 'Native Pronunciation'), ('speaking_sessions', 'Speaking Sessions'), ('weekly_exams', 'Weekly Exams'), ('study_materials', 'Study Materials'), ('mock_interviews', 'Mock Interviews'), ('visa_guidance', 'Visa Guidance'), ('career_counselling', 'Career Counselling'), ('hangul_writing', 'Hangul Writing'), ('speaking_practice', 'Speaking Practice'), ('listening_exercises', 'Listening Exercises'), ('topik_preparation', 'TOPIK Preparation'), ('weekly_assessments', 'Weekly Assessments'), ('small_batch_classes', 'Small Batch Classes'), ('career_guidance', 'Career Guidance'), ('tally_erp', 'Tally ERP'), ('quickbooks', 'QuickBooks'), ('vat_taxation', 'VAT & Taxation'), ('payroll', 'Payroll'), ('financial_statements', 'Financial Statements'), ('practical_projects', 'Practical Projects'), ('interview_preparation', 'Interview Preparation'), ('certificate', 'Certificate'), ('ms_word', 'MS Word'), ('excel', 'Excel'), ('powerpoint', 'PowerPoint'), ('internet', 'Internet'), ('email', 'Email'), ('typing_skills', 'Typing Skills'), ('basic_programming', 'Basic Programming'), ('project_work', 'Project Work')], max_length=50)),
                ('feature6', models.CharField(blank=True, choices=[('interactive_classes', 'Interactive Classes'), ('native_pronunciation', 'Native Pronunciation'), ('speaking_sessions', 'Speaking Sessions'), ('weekly_exams', 'Weekly Exams'), ('study_materials', 'Study Materials'), ('mock_interviews', 'Mock Interviews'), ('visa_guidance', 'Visa Guidance'), ('career_counselling', 'Career Counselling'), ('hangul_writing', 'Hangul Writing'), ('speaking_practice', 'Speaking Practice'), ('listening_exercises', 'Listening Exercises'), ('topik_preparation', 'TOPIK Preparation'), ('weekly_assessments', 'Weekly Assessments'), ('small_batch_classes', 'Small Batch Classes'), ('career_guidance', 'Career Guidance'), ('tally_erp', 'Tally ERP'), ('quickbooks', 'QuickBooks'), ('vat_taxation', 'VAT & Taxation'), ('payroll', 'Payroll'), ('financial_statements', 'Financial Statements'), ('practical_projects', 'Practical Projects'), ('interview_preparation', 'Interview Preparation'), ('certificate', 'Certificate'), ('ms_word', 'MS Word'), ('excel', 'Excel'), ('powerpoint', 'PowerPoint'), ('internet', 'Internet'), ('email', 'Email'), ('typing_skills', 'Typing Skills'), ('basic_programming', 'Basic Programming'), ('project_work', 'Project Work')], max_length=50)),
                ('feature7', models.CharField(blank=True, choices=[('interactive_classes', 'Interactive Classes'), ('native_pronunciation', 'Native Pronunciation'), ('speaking_sessions', 'Speaking Sessions'), ('weekly_exams', 'Weekly Exams'), ('study_materials', 'Study Materials'), ('mock_interviews', 'Mock Interviews'), ('visa_guidance', 'Visa Guidance'), ('career_counselling', 'Career Counselling'), ('hangul_writing', 'Hangul Writing'), ('speaking_practice', 'Speaking Practice'), ('listening_exercises', 'Listening Exercises'), ('topik_preparation', 'TOPIK Preparation'), ('weekly_assessments', 'Weekly Assessments'), ('small_batch_classes', 'Small Batch Classes'), ('career_guidance', 'Career Guidance'), ('tally_erp', 'Tally ERP'), ('quickbooks', 'QuickBooks'), ('vat_taxation', 'VAT & Taxation'), ('payroll', 'Payroll'), ('financial_statements', 'Financial Statements'), ('practical_projects', 'Practical Projects'), ('interview_preparation', 'Interview Preparation'), ('certificate', 'Certificate'), ('ms_word', 'MS Word'), ('excel', 'Excel'), ('powerpoint', 'PowerPoint'), ('internet', 'Internet'), ('email', 'Email'), ('typing_skills', 'Typing Skills'), ('basic_programming', 'Basic Programming'), ('project_work', 'Project Work')], max_length=50)),
                ('feature8', models.CharField(blank=True, choices=[('interactive_classes', 'Interactive Classes'), ('native_pronunciation', 'Native Pronunciation'), ('speaking_sessions', 'Speaking Sessions'), ('weekly_exams', 'Weekly Exams'), ('study_materials', 'Study Materials'), ('mock_interviews', 'Mock Interviews'), ('visa_guidance', 'Visa Guidance'), ('career_counselling', 'Career Counselling'), ('hangul_writing', 'Hangul Writing'), ('speaking_practice', 'Speaking Practice'), ('listening_exercises', 'Listening Exercises'), ('topik_preparation', 'TOPIK Preparation'), ('weekly_assessments', 'Weekly Assessments'), ('small_batch_classes', 'Small Batch Classes'), ('career_guidance', 'Career Guidance'), ('tally_erp', 'Tally ERP'), ('quickbooks', 'QuickBooks'), ('vat_taxation', 'VAT & Taxation'), ('payroll', 'Payroll'), ('financial_statements', 'Financial Statements'), ('practical_projects', 'Practical Projects'), ('interview_preparation', 'Interview Preparation'), ('certificate', 'Certificate'), ('ms_word', 'MS Word'), ('excel', 'Excel'), ('powerpoint', 'PowerPoint'), ('internet', 'Internet'), ('email', 'Email'), ('typing_skills', 'Typing Skills'), ('basic_programming', 'Basic Programming'), ('project_work', 'Project Work')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Advertisments',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumbnail', models.URLField()),
                ('redirect', models.URLField()),
                ('relatedAdvertisment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.courses')),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image1', models.URLField()),
                ('image2', models.URLField()),
                ('image3', models.URLField()),
                ('image4', models.URLField()),
                ('image5', models.URLField()),
                ('image6', models.URLField()),
                ('image7', models.URLField()),
                ('image8', models.URLField()),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.courses')),
            ],
        ),
        migrations.CreateModel(
            name='Mentors',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mentorname', models.CharField(max_length=30)),
                ('gender', models.BooleanField(default=True)),
                ('mentorimage', models.URLField()),
                ('description', models.TextField()),
                ('address', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('email', models.CharField(max_length=50)),
                ('facebookurl', models.URLField(default='https://www.facebook.com/dosmultiservices')),
                ('instagramurl', models.URLField(default='https://www.facebook.com/dosmultiservices')),
                ('linkedinurl', models.URLField(default='https://www.facebook.com/dosmultiservices')),
                ('twitterurl', models.URLField(default='https://www.facebook.com/dosmultiservices')),
                ('tiktokurl', models.URLField(default='https://www.facebook.com/dosmultiservices')),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courses.courses')),
            ],
        ),
    ]
