# Generated by Django 6.0.7 on 2026-08-07 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisments',
            name='relatedAdvertisment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='advertisements', to='courses.courses'),
        ),
        migrations.AlterField(
            model_name='courses',
            name='classTiming',
            field=models.CharField(choices=[('Morning Only', 'MORNING'), ('Afternoon Only', 'AFTERNOON'), ('Evening Only', 'EVENING'), ('Morning and Afternoon', 'MORNING | AFTERNOON'), ('Morning and Evening', 'MORNING | EVENING'), ('Afternoon and Evening', 'AFTERNOON | EVENING')], max_length=50),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='courses.courses'),
        ),
        migrations.AlterField(
            model_name='mentors',
            name='domain',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mentors', to='courses.courses'),
        ),
    ]
