# Generated by Django 6.0.7 on 2026-08-07 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_alter_advertisments_relatedadvertisment_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courses',
            name='feature1',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='feature2',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='feature3',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='feature4',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='feature5',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='feature6',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='feature7',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='feature8',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='languageLevel1',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='languageLevel2',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='languageLevel3',
        ),
        migrations.RemoveField(
            model_name='courses',
            name='languageLevel4',
        ),
        migrations.AlterField(
            model_name='courses',
            name='slug',
            field=models.CharField(choices=[('LANGUAGE', 'LANGUAGE'), ('PROFESSIONALS', 'PROFESSIONAL'), ('TRAINING', 'TRAINING')], max_length=15),
        ),
        migrations.CreateModel(
            name='Features',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature1', models.CharField(choices=[('interactive_classes', 'Interactive Classes'), ('native_pronunciation', 'Native Pronunciation'), ('speaking_sessions', 'Speaking Sessions'), ('weekly_exams', 'Weekly Exams'), ('study_materials', 'Study Materials'), ('mock_interviews', 'Mock Interviews'), ('visa_guidance', 'Visa Guidance'), ('career_counselling', 'Career Counselling'), ('hangul_writing', 'Hangul Writing'), ('speaking_practice', 'Speaking Practice'), ('listening_exercises', 'Listening Exercises'), ('topik_preparation', 'TOPIK Preparation'), ('weekly_assessments', 'Weekly Assessments'), ('small_batch_classes', 'Small Batch Classes'), ('career_guidance', 'Career Guidance'), ('tally_erp', 'Tally ERP'), ('quickbooks', 'QuickBooks'), ('vat_taxation', 'VAT & Taxation'), ('payroll', 'Payroll'), ('financial_statements', 'Financial Statements'), ('practical_projects', 'Practical Projects'), ('interview_preparation', 'Interview Preparation'), ('certificate', 'Certificate'), ('ms_word', 'MS Word'), ('excel', 'Excel'), ('powerpoint', 'PowerPoint'), ('internet', 'Internet'), ('email', 'Email'), ('typing_skills', 'Typing Skills'), ('basic_programming', 'Basic Programming'), ('project_work', 'Project Work')], max_length=50)),
                ('feature2', models.CharField(choices=[('interactive_classes', 'Interactive Classes'), ('native_pronunciation', 'Native Pronunciation'), ('speaking_sessions', 'Speaking Sessions'), ('weekly_exams', 'Weekly Exams'), ('study_materials', 'Study Materials'), ('mock_interviews', 'Mock Interviews'), ('visa_guidance', 'Visa Guidance'), ('career_counselling', 'Career Counselling'), ('hangul_writing', 'Hangul Writing'), ('speaking_practice', 'Speaking Practice'), ('listening_exercises', 'Listening Exercises'), ('topik_preparation', 'TOPIK Preparation'), ('weekly_assessments', 'Weekly Assessments'), ('small_batch_classes', 'Small Batch Classes'), ('career_guidance', 'Career Guidance'), ('tally_erp', 'Tally ERP'), ('quickbooks', 'QuickBooks'), ('vat_taxation', 'VAT & Taxation'), ('payroll', 'Payroll'), ('financial_statements', 'Financial Statements'), ('practical_projects', 'Practical Projects'), ('interview_preparation', 'Interview Preparation'), ('certificate', 'Certificate'), ('ms_word', 'MS Word'), ('excel', 'Excel'), ('powerpoint', 'PowerPoint'), ('internet', 'Internet'), ('email', 'Email'), ('typing_skills', 'Typing Skills'), ('basic_programming', 'Basic Programming'), ('project_work', 'Project Work')], max_length=50)),
                ('feature3', models.CharField(choices=[('interactive_classes', 'Interactive Classes'), ('native_pronunciation', 'Native Pronunciation'), ('speaking_sessions', 'Speaking Sessions'), ('weekly_exams', 'Weekly Exams'), ('study_materials', 'Study Materials'), ('mock_interviews', 'Mock Interviews'), ('visa_guidance', 'Visa Guidance'), ('career_counselling', 'Career Counselling'), ('hangul_writing', 'Hangul Writing'), ('speaking_practice', 'Speaking Practice'), ('listening_exercises', 'Listening Exercises'), ('topik_preparation', 'TOPIK Preparation'), ('weekly_assessments', 'Weekly Assessments'), ('small_batch_classes', 'Small Batch Classes'), ('career_guidance', 'Career Guidance'), ('tally_erp', 'Tally ERP'), ('quickbooks', 'QuickBooks'), ('vat_taxation', 'VAT & Taxation'), ('payroll', 'Payroll'), ('financial_statements', 'Financial Statements'), ('practical_projects', 'Practical Projects'), ('interview_preparation', 'Interview Preparation'), ('certificate', 'Certificate'), ('ms_word', 'MS Word'), ('excel', 'Excel'), ('powerpoint', 'PowerPoint'), ('internet', 'Internet'), ('email', 'Email'), ('typing_skills', 'Typing Skills'), ('basic_programming', 'Basic Programming'), ('project_work', 'Project Work')], max_length=50)),
                ('feature4', models.CharField(choices=[('interactive_classes', 'Interactive Classes'), ('native_pronunciation', 'Native Pronunciation'), ('speaking_sessions', 'Speaking Sessions'), ('weekly_exams', 'Weekly Exams'), ('study_materials', 'Study Materials'), ('mock_interviews', 'Mock Interviews'), ('visa_guidance', 'Visa Guidance'), ('career_counselling', 'Career Counselling'), ('hangul_writing', 'Hangul Writing'), ('speaking_practice', 'Speaking Practice'), ('listening_exercises', 'Listening Exercises'), ('topik_preparation', 'TOPIK Preparation'), ('weekly_assessments', 'Weekly Assessments'), ('small_batch_classes', 'Small Batch Classes'), ('career_guidance', 'Career Guidance'), ('tally_erp', 'Tally ERP'), ('quickbooks', 'QuickBooks'), ('vat_taxation', 'VAT & Taxation'), ('payroll', 'Payroll'), ('financial_statements', 'Financial Statements'), ('practical_projects', 'Practical Projects'), ('interview_preparation', 'Interview Preparation'), ('certificate', 'Certificate'), ('ms_word', 'MS Word'), ('excel', 'Excel'), ('powerpoint', 'PowerPoint'), ('internet', 'Internet'), ('email', 'Email'), ('typing_skills', 'Typing Skills'), ('basic_programming', 'Basic Programming'), ('project_work', 'Project Work')], max_length=50)),
                ('feature5', models.CharField(blank=True, choices=[('interactive_classes', 'Interactive Classes'), ('native_pronunciation', 'Native Pronunciation'), ('speaking_sessions', 'Speaking Sessions'), ('weekly_exams', 'Weekly Exams'), ('study_materials', 'Study Materials'), ('mock_interviews', 'Mock Interviews'), ('visa_guidance', 'Visa Guidance'), ('career_counselling', 'Career Counselling'), ('hangul_writing', 'Hangul Writing'), ('speaking_practice', 'Speaking Practice'), ('listening_exercises', 'Listening Exercises'), ('topik_preparation', 'TOPIK Preparation'), ('weekly_assessments', 'Weekly Assessments'), ('small_batch_classes', 'Small Batch Classes'), ('career_guidance', 'Career Guidance'), ('tally_erp', 'Tally ERP'), ('quickbooks', 'QuickBooks'), ('vat_taxation', 'VAT & Taxation'), ('payroll', 'Payroll'), ('financial_statements', 'Financial Statements'), ('practical_projects', 'Practical Projects'), ('interview_preparation', 'Interview Preparation'), ('certificate', 'Certificate'), ('ms_word', 'MS Word'), ('excel', 'Excel'), ('powerpoint', 'PowerPoint'), ('internet', 'Internet'), ('email', 'Email'), ('typing_skills', 'Typing Skills'), ('basic_programming', 'Basic Programming'), ('project_work', 'Project Work')], max_length=50)),
                ('feature6', models.CharField(blank=True, choices=[('interactive_classes', 'Interactive Classes'), ('native_pronunciation', 'Native Pronunciation'), ('speaking_sessions', 'Speaking Sessions'), ('weekly_exams', 'Weekly Exams'), ('study_materials', 'Study Materials'), ('mock_interviews', 'Mock Interviews'), ('visa_guidance', 'Visa Guidance'), ('career_counselling', 'Career Counselling'), ('hangul_writing', 'Hangul Writing'), ('speaking_practice', 'Speaking Practice'), ('listening_exercises', 'Listening Exercises'), ('topik_preparation', 'TOPIK Preparation'), ('weekly_assessments', 'Weekly Assessments'), ('small_batch_classes', 'Small Batch Classes'), ('career_guidance', 'Career Guidance'), ('tally_erp', 'Tally ERP'), ('quickbooks', 'QuickBooks'), ('vat_taxation', 'VAT & Taxation'), ('payroll', 'Payroll'), ('financial_statements', 'Financial Statements'), ('practical_projects', 'Practical Projects'), ('interview_preparation', 'Interview Preparation'), ('certificate', 'Certificate'), ('ms_word', 'MS Word'), ('excel', 'Excel'), ('powerpoint', 'PowerPoint'), ('internet', 'Internet'), ('email', 'Email'), ('typing_skills', 'Typing Skills'), ('basic_programming', 'Basic Programming'), ('project_work', 'Project Work')], max_length=50)),
                ('feature7', models.CharField(blank=True, choices=[('interactive_classes', 'Interactive Classes'), ('native_pronunciation', 'Native Pronunciation'), ('speaking_sessions', 'Speaking Sessions'), ('weekly_exams', 'Weekly Exams'), ('study_materials', 'Study Materials'), ('mock_interviews', 'Mock Interviews'), ('visa_guidance', 'Visa Guidance'), ('career_counselling', 'Career Counselling'), ('hangul_writing', 'Hangul Writing'), ('speaking_practice', 'Speaking Practice'), ('listening_exercises', 'Listening Exercises'), ('topik_preparation', 'TOPIK Preparation'), ('weekly_assessments', 'Weekly Assessments'), ('small_batch_classes', 'Small Batch Classes'), ('career_guidance', 'Career Guidance'), ('tally_erp', 'Tally ERP'), ('quickbooks', 'QuickBooks'), ('vat_taxation', 'VAT & Taxation'), ('payroll', 'Payroll'), ('financial_statements', 'Financial Statements'), ('practical_projects', 'Practical Projects'), ('interview_preparation', 'Interview Preparation'), ('certificate', 'Certificate'), ('ms_word', 'MS Word'), ('excel', 'Excel'), ('powerpoint', 'PowerPoint'), ('internet', 'Internet'), ('email', 'Email'), ('typing_skills', 'Typing Skills'), ('basic_programming', 'Basic Programming'), ('project_work', 'Project Work')], max_length=50)),
                ('feature8', models.CharField(blank=True, choices=[('interactive_classes', 'Interactive Classes'), ('native_pronunciation', 'Native Pronunciation'), ('speaking_sessions', 'Speaking Sessions'), ('weekly_exams', 'Weekly Exams'), ('study_materials', 'Study Materials'), ('mock_interviews', 'Mock Interviews'), ('visa_guidance', 'Visa Guidance'), ('career_counselling', 'Career Counselling'), ('hangul_writing', 'Hangul Writing'), ('speaking_practice', 'Speaking Practice'), ('listening_exercises', 'Listening Exercises'), ('topik_preparation', 'TOPIK Preparation'), ('weekly_assessments', 'Weekly Assessments'), ('small_batch_classes', 'Small Batch Classes'), ('career_guidance', 'Career Guidance'), ('tally_erp', 'Tally ERP'), ('quickbooks', 'QuickBooks'), ('vat_taxation', 'VAT & Taxation'), ('payroll', 'Payroll'), ('financial_statements', 'Financial Statements'), ('practical_projects', 'Practical Projects'), ('interview_preparation', 'Interview Preparation'), ('certificate', 'Certificate'), ('ms_word', 'MS Word'), ('excel', 'Excel'), ('powerpoint', 'PowerPoint'), ('internet', 'Internet'), ('email', 'Email'), ('typing_skills', 'Typing Skills'), ('basic_programming', 'Basic Programming'), ('project_work', 'Project Work')], max_length=50)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='courses.courses')),
            ],
        ),
        migrations.CreateModel(
            name='Languages',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('languageLevel1', models.CharField(blank=True, choices=[('A1', 'A1-GERMAN'), ('A2', 'A2-GERMAN'), ('B1', 'B1-GERMAN'), ('B2', 'B2-GERMAN'), ('TOPIK I', 'TOPIK I-KOREAN'), ('TOPIK II', 'TOPIK II-KOREAN'), ('Beginner', 'BEGINNER-KOREAN'), ('Intermediate', 'INTERMEDIATE-KOREAN'), ('Advanced', 'ADVANCED-KOREAN')], max_length=15)),
                ('languageLevel2', models.CharField(blank=True, choices=[('A1', 'A1-GERMAN'), ('A2', 'A2-GERMAN'), ('B1', 'B1-GERMAN'), ('B2', 'B2-GERMAN'), ('TOPIK I', 'TOPIK I-KOREAN'), ('TOPIK II', 'TOPIK II-KOREAN'), ('Beginner', 'BEGINNER-KOREAN'), ('Intermediate', 'INTERMEDIATE-KOREAN'), ('Advanced', 'ADVANCED-KOREAN')], max_length=15)),
                ('languageLevel3', models.CharField(blank=True, choices=[('A1', 'A1-GERMAN'), ('A2', 'A2-GERMAN'), ('B1', 'B1-GERMAN'), ('B2', 'B2-GERMAN'), ('TOPIK I', 'TOPIK I-KOREAN'), ('TOPIK II', 'TOPIK II-KOREAN'), ('Beginner', 'BEGINNER-KOREAN'), ('Intermediate', 'INTERMEDIATE-KOREAN'), ('Advanced', 'ADVANCED-KOREAN')], max_length=15)),
                ('languageLevel4', models.CharField(blank=True, choices=[('A1', 'A1-GERMAN'), ('A2', 'A2-GERMAN'), ('B1', 'B1-GERMAN'), ('B2', 'B2-GERMAN'), ('TOPIK I', 'TOPIK I-KOREAN'), ('TOPIK II', 'TOPIK II-KOREAN'), ('Beginner', 'BEGINNER-KOREAN'), ('Intermediate', 'INTERMEDIATE-KOREAN'), ('Advanced', 'ADVANCED-KOREAN')], max_length=15)),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='courses.courses')),
            ],
        ),
    ]
