# Generated by Django 6.0.7 on 2026-08-08 04:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0003_remove_courses_feature1_remove_courses_feature2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='features',
            name='feature1',
            field=models.CharField(choices=[('Interactive Classes', 'INTERACTIVE_CLASSES'), ('Native Pronunciation', 'NATIVE_PRONUNCIATION'), ('Speaking Sessions', 'SPEAKING_SESSIONS'), ('Weekly Exams', 'WEEKLY_EXAMS'), ('Study Materials', 'STUDY_MATERIALS'), ('Mock Interviews', 'MOCK_INTERVIEWS'), ('Visa Guidance', 'VISA_GUIDANCE'), ('Career Counselling', 'CAREER_COUNSELLING'), ('Hangul Writing', 'HANGUL_WRITING'), ('Speaking Practice', 'SPEAKING_PRACTICE'), ('Listening Exercises', 'LISTENING_EXERCISES'), ('TOPIK Preparation', 'TOPIK_PREPARATION'), ('Weekly Assessments', 'WEEKLY_ASSESSMENTS'), ('Small Batch Classes', 'SMALL_BATCH_CLASSES'), ('Career Guidance', 'CAREER_GUIDANCE'), ('Tally ERP', 'TALLY_ERP'), ('QuickBooks', 'QUICKBOOKS'), ('VAT & Taxation', 'VAT_TAXATION'), ('Payroll', 'PAYROLL'), ('Financial Statements', 'FINANCIAL_STATEMENTS'), ('Practical Projects', 'PRACTICAL_PROJECTS'), ('Interview Preparation', 'INTERVIEW_PREPARATION'), ('Certificate', 'CERTIFICATE'), ('MS Word', 'MS_WORD'), ('Excel', 'EXCEL'), ('PowerPoint', 'POWERPOINT'), ('Internet', 'INTERNET'), ('Email', 'EMAIL'), ('Typing Skills', 'TYPING_SKILLS'), ('Basic Programming', 'BASIC_PROGRAMMING'), ('Project Work', 'PROJECT_WORK')], max_length=50),
        ),
        migrations.AlterField(
            model_name='features',
            name='feature2',
            field=models.CharField(choices=[('Interactive Classes', 'INTERACTIVE_CLASSES'), ('Native Pronunciation', 'NATIVE_PRONUNCIATION'), ('Speaking Sessions', 'SPEAKING_SESSIONS'), ('Weekly Exams', 'WEEKLY_EXAMS'), ('Study Materials', 'STUDY_MATERIALS'), ('Mock Interviews', 'MOCK_INTERVIEWS'), ('Visa Guidance', 'VISA_GUIDANCE'), ('Career Counselling', 'CAREER_COUNSELLING'), ('Hangul Writing', 'HANGUL_WRITING'), ('Speaking Practice', 'SPEAKING_PRACTICE'), ('Listening Exercises', 'LISTENING_EXERCISES'), ('TOPIK Preparation', 'TOPIK_PREPARATION'), ('Weekly Assessments', 'WEEKLY_ASSESSMENTS'), ('Small Batch Classes', 'SMALL_BATCH_CLASSES'), ('Career Guidance', 'CAREER_GUIDANCE'), ('Tally ERP', 'TALLY_ERP'), ('QuickBooks', 'QUICKBOOKS'), ('VAT & Taxation', 'VAT_TAXATION'), ('Payroll', 'PAYROLL'), ('Financial Statements', 'FINANCIAL_STATEMENTS'), ('Practical Projects', 'PRACTICAL_PROJECTS'), ('Interview Preparation', 'INTERVIEW_PREPARATION'), ('Certificate', 'CERTIFICATE'), ('MS Word', 'MS_WORD'), ('Excel', 'EXCEL'), ('PowerPoint', 'POWERPOINT'), ('Internet', 'INTERNET'), ('Email', 'EMAIL'), ('Typing Skills', 'TYPING_SKILLS'), ('Basic Programming', 'BASIC_PROGRAMMING'), ('Project Work', 'PROJECT_WORK')], max_length=50),
        ),
        migrations.AlterField(
            model_name='features',
            name='feature3',
            field=models.CharField(choices=[('Interactive Classes', 'INTERACTIVE_CLASSES'), ('Native Pronunciation', 'NATIVE_PRONUNCIATION'), ('Speaking Sessions', 'SPEAKING_SESSIONS'), ('Weekly Exams', 'WEEKLY_EXAMS'), ('Study Materials', 'STUDY_MATERIALS'), ('Mock Interviews', 'MOCK_INTERVIEWS'), ('Visa Guidance', 'VISA_GUIDANCE'), ('Career Counselling', 'CAREER_COUNSELLING'), ('Hangul Writing', 'HANGUL_WRITING'), ('Speaking Practice', 'SPEAKING_PRACTICE'), ('Listening Exercises', 'LISTENING_EXERCISES'), ('TOPIK Preparation', 'TOPIK_PREPARATION'), ('Weekly Assessments', 'WEEKLY_ASSESSMENTS'), ('Small Batch Classes', 'SMALL_BATCH_CLASSES'), ('Career Guidance', 'CAREER_GUIDANCE'), ('Tally ERP', 'TALLY_ERP'), ('QuickBooks', 'QUICKBOOKS'), ('VAT & Taxation', 'VAT_TAXATION'), ('Payroll', 'PAYROLL'), ('Financial Statements', 'FINANCIAL_STATEMENTS'), ('Practical Projects', 'PRACTICAL_PROJECTS'), ('Interview Preparation', 'INTERVIEW_PREPARATION'), ('Certificate', 'CERTIFICATE'), ('MS Word', 'MS_WORD'), ('Excel', 'EXCEL'), ('PowerPoint', 'POWERPOINT'), ('Internet', 'INTERNET'), ('Email', 'EMAIL'), ('Typing Skills', 'TYPING_SKILLS'), ('Basic Programming', 'BASIC_PROGRAMMING'), ('Project Work', 'PROJECT_WORK')], max_length=50),
        ),
        migrations.AlterField(
            model_name='features',
            name='feature4',
            field=models.CharField(choices=[('Interactive Classes', 'INTERACTIVE_CLASSES'), ('Native Pronunciation', 'NATIVE_PRONUNCIATION'), ('Speaking Sessions', 'SPEAKING_SESSIONS'), ('Weekly Exams', 'WEEKLY_EXAMS'), ('Study Materials', 'STUDY_MATERIALS'), ('Mock Interviews', 'MOCK_INTERVIEWS'), ('Visa Guidance', 'VISA_GUIDANCE'), ('Career Counselling', 'CAREER_COUNSELLING'), ('Hangul Writing', 'HANGUL_WRITING'), ('Speaking Practice', 'SPEAKING_PRACTICE'), ('Listening Exercises', 'LISTENING_EXERCISES'), ('TOPIK Preparation', 'TOPIK_PREPARATION'), ('Weekly Assessments', 'WEEKLY_ASSESSMENTS'), ('Small Batch Classes', 'SMALL_BATCH_CLASSES'), ('Career Guidance', 'CAREER_GUIDANCE'), ('Tally ERP', 'TALLY_ERP'), ('QuickBooks', 'QUICKBOOKS'), ('VAT & Taxation', 'VAT_TAXATION'), ('Payroll', 'PAYROLL'), ('Financial Statements', 'FINANCIAL_STATEMENTS'), ('Practical Projects', 'PRACTICAL_PROJECTS'), ('Interview Preparation', 'INTERVIEW_PREPARATION'), ('Certificate', 'CERTIFICATE'), ('MS Word', 'MS_WORD'), ('Excel', 'EXCEL'), ('PowerPoint', 'POWERPOINT'), ('Internet', 'INTERNET'), ('Email', 'EMAIL'), ('Typing Skills', 'TYPING_SKILLS'), ('Basic Programming', 'BASIC_PROGRAMMING'), ('Project Work', 'PROJECT_WORK')], max_length=50),
        ),
        migrations.AlterField(
            model_name='features',
            name='feature5',
            field=models.CharField(blank=True, choices=[('Interactive Classes', 'INTERACTIVE_CLASSES'), ('Native Pronunciation', 'NATIVE_PRONUNCIATION'), ('Speaking Sessions', 'SPEAKING_SESSIONS'), ('Weekly Exams', 'WEEKLY_EXAMS'), ('Study Materials', 'STUDY_MATERIALS'), ('Mock Interviews', 'MOCK_INTERVIEWS'), ('Visa Guidance', 'VISA_GUIDANCE'), ('Career Counselling', 'CAREER_COUNSELLING'), ('Hangul Writing', 'HANGUL_WRITING'), ('Speaking Practice', 'SPEAKING_PRACTICE'), ('Listening Exercises', 'LISTENING_EXERCISES'), ('TOPIK Preparation', 'TOPIK_PREPARATION'), ('Weekly Assessments', 'WEEKLY_ASSESSMENTS'), ('Small Batch Classes', 'SMALL_BATCH_CLASSES'), ('Career Guidance', 'CAREER_GUIDANCE'), ('Tally ERP', 'TALLY_ERP'), ('QuickBooks', 'QUICKBOOKS'), ('VAT & Taxation', 'VAT_TAXATION'), ('Payroll', 'PAYROLL'), ('Financial Statements', 'FINANCIAL_STATEMENTS'), ('Practical Projects', 'PRACTICAL_PROJECTS'), ('Interview Preparation', 'INTERVIEW_PREPARATION'), ('Certificate', 'CERTIFICATE'), ('MS Word', 'MS_WORD'), ('Excel', 'EXCEL'), ('PowerPoint', 'POWERPOINT'), ('Internet', 'INTERNET'), ('Email', 'EMAIL'), ('Typing Skills', 'TYPING_SKILLS'), ('Basic Programming', 'BASIC_PROGRAMMING'), ('Project Work', 'PROJECT_WORK')], max_length=50),
        ),
        migrations.AlterField(
            model_name='features',
            name='feature6',
            field=models.CharField(blank=True, choices=[('Interactive Classes', 'INTERACTIVE_CLASSES'), ('Native Pronunciation', 'NATIVE_PRONUNCIATION'), ('Speaking Sessions', 'SPEAKING_SESSIONS'), ('Weekly Exams', 'WEEKLY_EXAMS'), ('Study Materials', 'STUDY_MATERIALS'), ('Mock Interviews', 'MOCK_INTERVIEWS'), ('Visa Guidance', 'VISA_GUIDANCE'), ('Career Counselling', 'CAREER_COUNSELLING'), ('Hangul Writing', 'HANGUL_WRITING'), ('Speaking Practice', 'SPEAKING_PRACTICE'), ('Listening Exercises', 'LISTENING_EXERCISES'), ('TOPIK Preparation', 'TOPIK_PREPARATION'), ('Weekly Assessments', 'WEEKLY_ASSESSMENTS'), ('Small Batch Classes', 'SMALL_BATCH_CLASSES'), ('Career Guidance', 'CAREER_GUIDANCE'), ('Tally ERP', 'TALLY_ERP'), ('QuickBooks', 'QUICKBOOKS'), ('VAT & Taxation', 'VAT_TAXATION'), ('Payroll', 'PAYROLL'), ('Financial Statements', 'FINANCIAL_STATEMENTS'), ('Practical Projects', 'PRACTICAL_PROJECTS'), ('Interview Preparation', 'INTERVIEW_PREPARATION'), ('Certificate', 'CERTIFICATE'), ('MS Word', 'MS_WORD'), ('Excel', 'EXCEL'), ('PowerPoint', 'POWERPOINT'), ('Internet', 'INTERNET'), ('Email', 'EMAIL'), ('Typing Skills', 'TYPING_SKILLS'), ('Basic Programming', 'BASIC_PROGRAMMING'), ('Project Work', 'PROJECT_WORK')], max_length=50),
        ),
        migrations.AlterField(
            model_name='features',
            name='feature7',
            field=models.CharField(blank=True, choices=[('Interactive Classes', 'INTERACTIVE_CLASSES'), ('Native Pronunciation', 'NATIVE_PRONUNCIATION'), ('Speaking Sessions', 'SPEAKING_SESSIONS'), ('Weekly Exams', 'WEEKLY_EXAMS'), ('Study Materials', 'STUDY_MATERIALS'), ('Mock Interviews', 'MOCK_INTERVIEWS'), ('Visa Guidance', 'VISA_GUIDANCE'), ('Career Counselling', 'CAREER_COUNSELLING'), ('Hangul Writing', 'HANGUL_WRITING'), ('Speaking Practice', 'SPEAKING_PRACTICE'), ('Listening Exercises', 'LISTENING_EXERCISES'), ('TOPIK Preparation', 'TOPIK_PREPARATION'), ('Weekly Assessments', 'WEEKLY_ASSESSMENTS'), ('Small Batch Classes', 'SMALL_BATCH_CLASSES'), ('Career Guidance', 'CAREER_GUIDANCE'), ('Tally ERP', 'TALLY_ERP'), ('QuickBooks', 'QUICKBOOKS'), ('VAT & Taxation', 'VAT_TAXATION'), ('Payroll', 'PAYROLL'), ('Financial Statements', 'FINANCIAL_STATEMENTS'), ('Practical Projects', 'PRACTICAL_PROJECTS'), ('Interview Preparation', 'INTERVIEW_PREPARATION'), ('Certificate', 'CERTIFICATE'), ('MS Word', 'MS_WORD'), ('Excel', 'EXCEL'), ('PowerPoint', 'POWERPOINT'), ('Internet', 'INTERNET'), ('Email', 'EMAIL'), ('Typing Skills', 'TYPING_SKILLS'), ('Basic Programming', 'BASIC_PROGRAMMING'), ('Project Work', 'PROJECT_WORK')], max_length=50),
        ),
        migrations.AlterField(
            model_name='features',
            name='feature8',
            field=models.CharField(blank=True, choices=[('Interactive Classes', 'INTERACTIVE_CLASSES'), ('Native Pronunciation', 'NATIVE_PRONUNCIATION'), ('Speaking Sessions', 'SPEAKING_SESSIONS'), ('Weekly Exams', 'WEEKLY_EXAMS'), ('Study Materials', 'STUDY_MATERIALS'), ('Mock Interviews', 'MOCK_INTERVIEWS'), ('Visa Guidance', 'VISA_GUIDANCE'), ('Career Counselling', 'CAREER_COUNSELLING'), ('Hangul Writing', 'HANGUL_WRITING'), ('Speaking Practice', 'SPEAKING_PRACTICE'), ('Listening Exercises', 'LISTENING_EXERCISES'), ('TOPIK Preparation', 'TOPIK_PREPARATION'), ('Weekly Assessments', 'WEEKLY_ASSESSMENTS'), ('Small Batch Classes', 'SMALL_BATCH_CLASSES'), ('Career Guidance', 'CAREER_GUIDANCE'), ('Tally ERP', 'TALLY_ERP'), ('QuickBooks', 'QUICKBOOKS'), ('VAT & Taxation', 'VAT_TAXATION'), ('Payroll', 'PAYROLL'), ('Financial Statements', 'FINANCIAL_STATEMENTS'), ('Practical Projects', 'PRACTICAL_PROJECTS'), ('Interview Preparation', 'INTERVIEW_PREPARATION'), ('Certificate', 'CERTIFICATE'), ('MS Word', 'MS_WORD'), ('Excel', 'EXCEL'), ('PowerPoint', 'POWERPOINT'), ('Internet', 'INTERNET'), ('Email', 'EMAIL'), ('Typing Skills', 'TYPING_SKILLS'), ('Basic Programming', 'BASIC_PROGRAMMING'), ('Project Work', 'PROJECT_WORK')], max_length=50),
        ),
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('students', models.IntegerField()),
                ('mentors', models.IntegerField()),
                ('successRate', models.IntegerField()),
                ('batches', models.IntegerField()),
                ('domain', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='courses.courses')),
            ],
        ),
    ]
