# Generated by Django 6.0.7 on 2026-08-08 11:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0004_alter_features_feature1_alter_features_feature2_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='features',
            name='domain',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='features', to='courses.courses'),
        ),
        migrations.AlterField(
            model_name='gallery',
            name='domain',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='gallery', to='courses.courses'),
        ),
        migrations.AlterField(
            model_name='languages',
            name='domain',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='languages', to='courses.courses'),
        ),
        migrations.AlterField(
            model_name='statistics',
            name='domain',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='courses.courses'),
        ),
    ]
