# Generated by Django 6.0.7 on 2026-08-07 12:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employees',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.URLField()),
                ('address', models.CharField(blank=True, default='Confidential!', max_length=255)),
                ('description', models.TextField()),
                ('role', models.CharField(choices=[('Founder', 'FOUNDER'), ('Managing Director', 'MANAGING DIRECTOR'), ('Director', 'DIRECTOR'), ('Chief Executive Officer', 'CHIEF EXECUTIVE OFFICER'), ('Chief Operating Officer', 'CHIEF OPERATING OFFICER'), ('Principal', 'PRINCIPAL'), ('Academic Coordinator', 'ACADEMIC COORDINATOR'), ('Department Head', 'DEPARTMENT HEAD'), ('Teacher', 'TEACHER'), ('Instructor', 'INSTRUCTOR'), ('Trainer', 'TRAINER'), ('Language Instructor', 'LANGUAGE INSTRUCTOR'), ('IT Instructor', 'IT INSTRUCTOR'), ('Accounting Trainer', 'ACCOUNTING TRAINER'), ('Receptionist', 'RECEPTIONIST'), ('Counselor', 'COUNSELOR'), ('Admission Officer', 'ADMISSION OFFICER'), ('Student', 'STUDENT'), ('Intern', 'INTERN'), ('Marketing Executive', 'MARKETING EXECUTIVE'), ('HR Officer', 'HR OFFICER'), ('Finance Officer', 'FINANCE OFFICER'), ('Accountant', 'ACCOUNTANT'), ('Office Assistant', 'OFFICE ASSISTANT'), ('Administrative Officer', 'ADMINISTRATIVE OFFICER'), ('IT Support', 'IT SUPPORT'), ('Software Developer', 'SOFTWARE DEVELOPER'), ('UI/UX Designer', 'UI/UX DESIGNER'), ('Graphic Designer', 'GRAPHIC DESIGNER'), ('Content Writer', 'CONTENT WRITER'), ('Social Media Manager', 'SOCIAL MEDIA MANAGER'), ('Photographer', 'PHOTOGRAPHER'), ('Videographer', 'VIDEOGRAPHER'), ('Volunteer', 'VOLUNTEER'), ('Member', 'MEMBER')], default='Member', max_length=30)),
                ('gender', models.BooleanField(default=True)),
                ('phoneNumber', models.CharField(blank=True, default='Confidential!', max_length=15)),
                ('facebook', models.URLField(blank=True)),
                ('instagram', models.URLField(blank=True)),
                ('tiktok', models.URLField(blank=True)),
                ('linkedin', models.URLField(blank=True)),
                ('twitter', models.URLField(blank=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Stories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('image', models.URLField()),
                ('address', models.CharField(blank=True, default='Confidential!', max_length=255)),
                ('description', models.TextField()),
                ('enrolled_in', models.CharField(choices=[('German', 'GERMAN LANGUAGE'), ('Korean', 'KOREAN LANGUAGE'), ('Accounting', 'ACCOUNTING TRAINING'), ('Computer', 'COMPUTER TRAINING')], max_length=30)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
